server:
  port: 8080
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: 123456
    key-password: 123456
    key-alias: mykey
    key-store-type: JKS
  servlet:
    session:
      cookie:
        same-site: none  #修复跨站问题 前端域名是http 后端是https 如果不显式设置 浏览器就不会发送cookie 也可以通过升级前端为https解决


spring:

  datasource:
    url: jdbc:mysql://localhost:3306/ocp?createDatabaseIfNotExist=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    throw-exception-if- no-handler-found: true
    path match:
      matching-strategy: ant_path_matcher
  web:
    resources:
        static-locations: classpath:/static/
  mail:
    host: smtp.qq.com
    port: 465
    username: 2309996590@qq.com
    password: vftjevjboezidjaf
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB