server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ocp?createDatabaseIfNotExist=true
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    throw-exception-if- no-handler-found: true
  web:
    resources:
        static-locations: classpath:/static/
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update