server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ocp?createDatabaseIfNotExist=true
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    throw-exception-if- no-handler-found: true
    path match:
      matching-strategy: ant_path_matcher
  web:
    resources:
        static-locations: classpath:/static/
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB